name = "app"
version = "1.0.0"
description = "Documentation for Lustre and its companion packages."

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre-labs.github.io" }
links = [
  { title = "Website", href = "https://lustre-labs.github.io" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.32"
jot = "~> 0.1"
lustre = "~> 3.0"
lustre_ui = "~> 0.2"
tom = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 0.10"
lustre_ssg = "~> 0.2"
simplifile = "~> 1.0"
